/**
 * Fetch the latin subsets of the site's three typefaces and write a
 * self-hosted @font-face sheet, so the site makes no third-party requests.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public', 'fonts');

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36';

/* Two voices only: a serif for display and a neutral sans for text. The
   monospace instrument layer was part of the old design and is gone. */
const families = [
  { css: 'Instrument+Serif:ital@0;1', stack: 'Instrument Serif', style: 'serif' },
  { css: 'Inter:wght@400;500', stack: 'Inter', style: 'sans' },
];

const url = `https://fonts.googleapis.com/css2?${families
  .map((f) => `family=${f.css}`)
  .join('&')}&display=swap`;

const res = await fetch(url, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
const css = await res.text();

/** Split the sheet into @font-face blocks and keep the latin ones. */
const blocks = css.match(/\/\*[^*]*\*\/\s*@font-face\s*\{[^}]*\}/g) || [];
const latin = blocks.filter((block) => /U\+0000-00FF/.test(block));

if (latin.length === 0) {
  throw new Error('No latin @font-face blocks found — Google Fonts markup may have changed.');
}

await mkdir(outDir, { recursive: true });

const familiesSeen = new Map();
const sheet = [];

for (const block of latin) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() || '400';
  const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() || 'normal';
  const src = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
  if (!family || !src) continue;

  const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const file = `${slug}-${weight.replace(/\s+/g, '_')}-${style}.woff2`;

  const bin = await fetch(src, { headers: { 'User-Agent': UA } });
  if (!bin.ok) throw new Error(`Failed to fetch ${src} (${bin.status})`);
  await writeFile(join(outDir, file), Buffer.from(await bin.arrayBuffer()));

  familiesSeen.set(family, true);
  sheet.push({ family, weight, style, file, range });
}

sheet.sort((a, b) => a.family.localeCompare(b.family) || Number(a.weight) - Number(b.weight));

const out = [
  '/* Self-hosted. Generated by tools/fetch-fonts.mjs — no CDN, no tracking. */',
  '',
  ...sheet.map((face) =>
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url('/fonts/${face.file}') format('woff2');`,
      face.range ? `  unicode-range: ${face.range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  ),
].join('\n\n');

await writeFile(join(root, 'src', 'styles', 'fonts.css'), `${out}\n`);

console.log(`Downloaded ${sheet.length} latin faces for: ${[...familiesSeen.keys()].join(', ')}`);
for (const face of sheet) console.log(`  ${face.family} ${face.weight} ${face.style} -> ${face.file}`);
